apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: haproxy-ing
  namespace: school-portal-app-3-tier
  annotations:
spec:
  ingressClassName: haproxy
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
      - path: /student 
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 3500
      - path: /teacher
        pathType: Prefix
        backend:
          service:
            name: ratings-service
            port:
              number: 3500
      - path:  /addteacher
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 3500
      - path:  /addstudent
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 3500
